/**
 * Glossário de palavras difíceis em português e suas alternativas mais simples
 * Organizado em ordem alfabética para facilitar a manutenção
 * Inclui termos gerais, jurídicos e expressões comuns.
 */
const GLOSSARY = {
  // A
  "a posteriori": ["depois", "posteriormente", "após a experiência"],
  "a priori": ["antes", "previamente", "antes da experiência"],
  "ab initio": ["desde o começo", "do início"],
  "abdicar": ["desistir", "renunciar", "abrir mão de"],
  "abnegação": ["sacrifício", "dedicação", "desprendimento"],
  "abrupto": ["repentino", "súbito", "inesperado"],
  "abstrato": ["teórico", "não concreto", "ideal"],
  "acepção": ["significado", "sentido", "interpretação"],
  "acirrado": ["intenso", "forte", "disputado"],
  "acórdão": ["decisão do tribunal", "decisão de vários juízes"],
  "ação civil pública": ["processo coletivo", "ação para proteger interesses da sociedade"],
  "ação de alimentos": ["pedido de pensão alimentícia"],
  "ação de despejo": ["pedido para desocupar imóvel alugado"],
  "ação de divórcio": ["pedido de separação legal"],
  "ação de execução": ["cobrança judicial de dívida"],
  "ação de guarda": ["pedido para definir quem cuida da criança/adolescente"],
  "ação de indenização": ["pedido de reparação por danos"],
  "ação de inventário": ["processo para dividir herança"],
  "ação monitória": ["ação para cobrar dívida com prova escrita"],
  "ação penal": ["processo criminal", "processo por crime"],
  "ação revisional": ["pedido para rever cláusulas de contrato"],
  "acessibilidade": ["facilidade de acesso", "condições para que todos possam usar"],
  "ad cautelam": ["por precaução", "por segurança"],
  "ad hoc": ["para este fim", "específico para o caso", "para isso"],
  "adágio": ["provérbio", "ditado popular"],
  "ademais": ["além disso", "também"],
  "adjunto": ["associado", "junto", "auxiliar"],
  "admoestar": ["repreender", "advertir", "chamar a atenção"],
  "adquirir": ["comprar", "conseguir", "obter"],
  "adversidade": ["dificuldade", "problema", "contratempo"],
  "advogado": ["defensor", "representante legal"],
  "afável": ["amigável", "gentil", "cortês"],
  "afeta": ["prejudica", "influencia", "atinge"],
  "afirmativa": ["resposta positiva", "sim", "confirmação"],
  "afligir": ["preocupar", "angustiar", "causar sofrimento"],
  "agravo": ["recurso contra decisão intermediária", "pedido para rever decisão"],
  "agravo de instrumento": ["recurso contra decisão urgente no processo"],
  "alegações finais": ["últimas argumentações das partes antes da decisão"],
  "alienação": ["venda", "transferência de propriedade"],
  "aludir": ["mencionar", "referir-se a"],
  "alusão": ["referência", "menção"],
  "ambíguo": ["duvidoso", "incerto", "com mais de um sentido"],
  "amicus curiae": ["amigo da corte", "pessoa ou entidade que ajuda o juiz com informações"],
  "analisar": ["examinar", "ver", "estudar"],
  "análogo": ["semelhante", "parecido"],
  "antecipadamente somos gratos": ["agradecemos desde já"],
  "anuência": ["autorização", "permissão", "consentimento"],
  "ao ensejo": ["neste momento", "aproveitando a oportunidade"],
  "apelação": ["recurso contra a sentença", "pedido para tribunal superior rever decisão final"],
  "apogeu": ["auge", "topo", "ponto mais alto"],
  "apregoar": ["anunciar", "proclamar", "divulgar"],
  "aproveitando o ensejo": ["aproveitando a oportunidade"],
  "arcaico": ["antigo", "ultrapassado", "fora de uso"],
  "ardiloso": ["esperto", "astuto", "malicioso"],
  "arguir": ["questionar", "alegar", "apresentar como argumento"],
  "arquivar": ["encerrar o processo", "guardar"],
  "arrazoado": ["argumentação", "exposição de motivos"],
  "arbitragem": ["decisão de conflito por um árbitro (fora do tribunal)"],
  "assistência judiciária": ["ajuda legal gratuita", "advogado de graça fornecido pelo Estado"],
  "astreintes": ["multa diária por descumprimento de ordem judicial"],
  "audiência de custódia": ["apresentação do preso ao juiz em 24h"],
  "audiência de instrução e julgamento": ["reunião para ouvir partes, testemunhas e produzir provas"],
  "auspicioso": ["promissor", "favorável", "de bom presságio"],
  "autarquia": ["entidade pública com autonomia administrativa e financeira"],
  "autos": ["documentos do processo", "o processo em si"],
  "autor": ["quem entra com o processo", "quem faz o pedido na justiça"],
  "averiguar": ["investigar", "verificar", "apurar"],
  "azo": ["motivo", "causa", "oportunidade"],

  // B
  "barreiras": ["obstáculos", "dificuldades", "impedimentos"],
  "beligerante": ["agressivo", "combativo", "em guerra"],
  "bem de família": ["casa da família protegida por lei contra dívidas"],
  "bem fungível": ["bem que pode ser trocado por outro igual (ex: dinheiro, grãos)"],
  "beneplácito": ["aprovação", "consentimento", "autorização"],
  "benesse": ["favor", "vantagem", "privilégio"],
  "burocracia": ["papelada", "processos administrativos complexos", "excesso de formalidades"],

  // C
  "cabal": ["completo", "perfeito", "indiscutível"],
  "capcioso": ["enganoso", "traiçoeiro", "que induz ao erro"],
  "carta magna": ["Constituição Federal", "lei maior do país"],
  "carta precatória": ["pedido de um juiz para outro juiz de comarca diferente realizar um ato processual"],
  "carta rogatória": ["pedido de um juiz para autoridade judicial de outro país"],
  "cautelar": ["medida preventiva", "medida de precaução"],
  "celeridade": ["rapidez", "agilidade", "velocidade"],
  "certidão de objeto e pé": ["documento que resume o estado atual do processo"],
  "cessão": ["doação", "transferência de direitos ou bens"],
  "circunspecção": ["cautela", "prudência", "reserva"],
  "citação": ["chamado oficial para o réu se defender no processo", "convocação"],
  "citar": ["chamar para o processo", "convocar oficialmente"],
  "cláusula pétrea": ["artigo da Constituição que não pode ser mudado"],
  "cobiça": ["desejo excessivo", "ganância", "ambição desmedida"],
  "cognitivo": ["mental", "intelectual", "relacionado ao conhecimento"],
  "coisa julgada": ["decisão judicial definitiva, que não pode mais ser modificada"],
  "colendo": ["respeitável", "ilustre (usado para tribunais superiores)"],
  "cominar": ["aplicar pena", "ameaçar com punição"],
  "compelir": ["forçar", "obrigar", "constranger"],
  "compêndio": ["resumo", "manual", "sumário"],
  "competência": ["atribuição legal para julgar um caso", "capacidade"],
  "comunique-se à parte interessada": ["avise quem tem interesse"],
  "concessa venia": ["com o devido respeito", "com a sua permissão"],
  "conciliação": ["acordo entre as partes para resolver o conflito"],
  "concepção": ["ideia", "conceito", "entendimento"],
  "conquanto": ["embora", "apesar de", "ainda que"],
  "conjuntura": ["situação", "contexto", "cenário"],
  "consignar": ["registrar", "declarar", "depositar judicialmente"],
  "constatar": ["verificar", "perceber", "confirmar"],
  "constituinte": ["que faz parte de algo", "membro de assembleia que elabora constituição"],
  "constranger": ["forçar", "obrigar", "causar vergonha"],
  "consumar": ["realizar completamente", "finalizar", "efetivar"],
  "contestação": ["defesa do réu", "resposta do réu à acusação inicial"],
  "contravenção penal": ["infração leve", "crime de menor gravidade"],
  "contraditório": ["direito de resposta", "direito de se defender e apresentar sua versão"],
  "contrato": ["acordo formal", "compromisso legal entre partes"],
  "contumácia": ["desobediência persistente a uma ordem judicial", "teimosia"],
  "corolário": ["consequência lógica", "resultado direto"],
  "corroborar": ["confirmar", "apoiar", "reforçar uma ideia"],

  // D
  "dano emergente": ["prejuízo direto e imediato causado por um ato"],
  "dano moral": ["prejuízo emocional", "ofensa à honra, imagem ou dignidade"],
  "data máxima vênia": ["com o máximo respeito", "pedindo licença (para discordar)"],
  "de antemão": ["antecipadamente", "previamente"],
  "de cujus": ["pessoa falecida (no inventário)", "o falecido"],
  "decadência": ["perda do direito por não exercê-lo no prazo legal"],
  "decisão interlocutória": ["decisão do juiz durante o processo (não é a final)"],
  "decisum": ["a decisão judicial", "o que foi decidido"],
  "deficiência auditiva": ["dificuldade de ouvir", "surdez"],
  "deficiência intelectual": ["dificuldade de aprendizado e compreensão"],
  "deficiência visual": ["baixa visão", "cegueira"],
  "deferido": ["aprovado", "aceito", "concedido"],
  "deferir": ["aceitar", "conceder", "aprovar (um pedido)"],
  "defeso": ["proibido", "vedado"],
  "defiro o pedido": ["aceito o pedido"],
  "deliberar": ["decidir após discussão ou reflexão", "resolver"],
  "demais": ["outros", "restantes"],
  "denegrir": ["difamar", "manchar a reputação", "prejudicar a imagem"],
  "denominação": ["nome", "título", "designação"],
  "denúncia": ["acusação formal no processo criminal feita pelo Ministério Público"],
  "deprecar": ["pedir (a outro juiz, por carta precatória)"],
  "desarrazoado": ["sem razão", "injustificado", "absurdo"],
  "desiderato colimado": ["objetivo desejado", "meta pretendida"],
  "desdenhar": ["desprezar", "menosprezar", "fazer pouco caso"],
  "desiderato": ["objetivo", "meta", "o que se deseja alcançar"],
  "deslinde": ["solução", "resolução", "esclarecimento final"],
  "despacho": ["ordem do juiz para dar andamento ao processo (não decide o mérito)"],
  "déspotas": ["tiranos", "opressores", "governantes autoritários"],
  "destarte": ["assim", "dessa forma", "desse modo"],
  "devido ao fato de que": ["porque", "já que"],
  "dilação": ["prorrogação de prazo", "adiamento"],
  "diligência": ["cuidado", "atenção", "ato realizado por oficial de justiça fora do cartório"],
  "dirimir": ["resolver", "solucionar (dúvida, conflito)"],
  "direito à informação": ["direito de saber", "direito de ter acesso a informações"],
  "direito à justiça": ["direito de buscar a justiça", "acesso ao sistema judicial"],
  "disruptivo": ["inovador", "revolucionário", "que rompe com o tradicional"],
  "dissensão": ["discordância", "desacordo", "divergência"],
  "dissimulação": ["fingimento", "disfarce", "ocultação da verdade"],
  "distensão": ["relaxamento", "alívio de tensão"],
  "distinguir": ["diferenciar", "separar", "reconhecer as diferenças"],
  "distribuição": ["sorteio do processo para uma vara específica", "encaminhamento inicial"],
  "diuturno": ["que dura muito tempo", "constante", "de dia e de noite"],
  "dolo": ["intenção de cometer o crime ou prejudicar", "má-fé"],
  "douto": ["sábio", "erudito (usado para se referir a juízes, promotores)"],

  // E
  "eclodir": ["surgir", "aparecer", "manifestar-se"],
  "efêmero": ["passageiro", "temporário", "de curta duração"],
  "eficácia": ["capacidade de produzir o efeito desejado"],
  "efigie": ["imagem", "representação", "retrato"],
  "égide": ["proteção", "amparo", "tutela"],
  "egrégio": ["ilustre", "notável", "respeitável (usado para tribunais)"],
  "elencar": ["listar", "enumerar", "relacionar"],
  "elidir": ["eliminar", "suprimir", "anular"],
  "elucubração": ["reflexão profunda", "pensamento demorado", "meditação"],
  "embargos": ["tipo de recurso para esclarecer ou corrigir decisão judicial"],
  "embargos de declaração": ["recurso para pedir esclarecimento ou correção de omissão/contradição na decisão"],
  "embuste": ["mentira", "engano", "fraude"],
  "em detrimento de": ["prejudicando", "em prejuízo de"],
  "em face de": ["diante de", "perante", "considerando"],
  "em que pese": ["apesar de", "embora"],
  "em razão de": ["por causa de", "devido a"],
  "em se tratando de": ["sobre", "quando se trata de"],
  "em suma": ["resumindo", "em resumo"],
  "em virtude de": ["por causa de", "devido a"],
  "emancipar": ["tornar independente", "libertar (menor de idade da tutela)"],
  "ementa": ["resumo da decisão judicial", "sumário do julgado"],
  "emergir": ["surgir", "aparecer", "vir à tona"],
  "eminente": ["elevado", "importante", "prestes a acontecer"],
  "empatia": ["compreensão", "sensibilidade", "capacidade de se colocar no lugar do outro"],
  "empecilho": ["obstáculo", "problema", "dificuldade"],
  "encarecemos a Vossa Senhoria": ["solicitamos encarecidamente", "pedimos com insistência"],
  "ensejar": ["causar", "provocar", "dar oportunidade para"],
  "ensejo": ["oportunidade", "ocasião", "momento favorável"],
  "entendimento": ["interpretação", "opinião (dos tribunais)"],
  "equidade": ["igualdade", "justiça", "tratamento justo"],
  "erga omnes": ["válido para todos", "com efeito geral"],
  "erigir": ["construir", "fundar", "estabelecer"],
  "erudito": ["culto", "sábio", "que tem muito conhecimento"],
  "escopo": ["objetivo", "finalidade", "propósito"],
  "esdrúxulo": ["estranho", "bizarro", "excêntrico"],
  "espúrio": ["falso", "ilegítimo", "não autêntico"],
  "estipular": ["definir", "combinar", "estabelecer (condições)"],
  "exacerbar": ["intensificar", "agravar", "piorar"],
  "exarar": ["emitir (despacho, parecer)", "registrar por escrito"],
  "exaustivo": ["completo", "detalhado", "que esgota o assunto"],
  "excelso": ["muito elevado", "sublime", "superior (usado para o STF)"],
  "excerto": ["trecho", "parte", "fragmento"],
  "execução": ["fase de cumprimento da decisão judicial", "cobrança forçada"],
  "executar": ["fazer", "cumprir", "realizar"],
  "exequível": ["que pode ser executado", "realizável"],
  "eximir": ["dispensar", "isentar", "livrar de obrigação"],
  "exímio": ["excelente", "perfeito", "muito habilidoso"],
  "êxito": ["sucesso", "bom resultado"],
  "exordial": ["petição inicial", "primeiro pedido no processo"],
  "exorbitante": ["excessivo", "exagerado", "muito alto (preço)"],
  "expeça-se mandado": ["faça a ordem judicial", "emita-se a ordem"],
  "expert": ["especialista", "perito"],
  "expertise": ["conhecimento especializado", "habilidade técnica"],
  "expiar": ["pagar por (culpa, crime)", "sofrer as consequências"],
  "explicitar": ["tornar claro", "explicar detalhadamente"],
  "expor": ["apresentar", "mostrar", "declarar"],
  "ex tunc": ["desde o início", "com efeito retroativo (que volta ao passado)"],
  "ex nunc": ["a partir de agora", "com efeito para o futuro (não retroage)"],
  "extra petita": ["decisão fora do que foi pedido pelas partes"],

  // F
  "faccioso": ["parcial", "tendencioso", "que favorece um lado"],
  "factível": ["possível", "realizável", "que pode ser feito"],
  "facultar": ["permitir", "dar a opção", "autorizar"],
  "falibilidade": ["possibilidade de erro", "imperfeição"],
  "famigerado": ["famoso (geralmente por algo ruim)", "mal afamado", "célebre"],
  "feedback": ["retorno", "avaliação", "opinião sobre algo"],
  "fiança": ["garantia de pagamento de dívida por terceiro"],
  "findar": ["terminar", "acabar", "concluir"],
  "flagrante": ["no momento do crime", "evidente"],
  "fls.": ["folhas (abreviação para indicar página do processo)"],
  "fomentar": ["incentivar", "promover", "estimular"],
  "foro": ["local onde se discute uma causa judicial", "competência territorial"],
  "fortuito": ["casual", "acidental", "imprevisto"],
  "fulcral": ["central", "essencial", "fundamental"],
  "fulcro": ["base", "fundamento", "apoio"],
  "fumus boni iuris": ["aparência de bom direito", "sinal de que o direito provavelmente existe"],

  // G
  "garantista": ["que defende as garantias individuais e processuais"],
  "genérico": ["geral", "não específico", "abrangente"],
  "grandiloquente": ["pomposo", "exagerado no falar", "retórico"],
  "gratuito": ["de graça", "sem custo"],
  "gravame": ["ônus", "encargo", "restrição sobre um bem"],
  "grosso modo": ["de modo geral", "aproximadamente", "sem detalhes"],

  // H
  "habeas corpus": ["ação para proteger o direito de liberdade contra prisão ilegal"],
  "haja vista": ["considerando", "tendo em vista", "levando em conta"],
  "hebdomadário": ["semanal", "que ocorre toda semana"],
  "hediondo": ["nojento", "repugnante", "crime muito grave"],
  "hermenêutica": ["arte ou ciência da interpretação (de textos legais)"],
  "heterogêneo": ["diversificado", "variado", "composto de partes diferentes"],
  "hígido": ["saudável", "firme", "sólido (argumento)"],
  "hipossuficiente": ["pessoa com poucos recursos financeiros", "necessitado"],
  "hipotético": ["suposto", "imaginário", "baseado em hipótese"],
  "homologar": ["confirmar judicialmente (um acordo, uma sentença estrangeira)", "aprovar oficialmente"],
  "honorários de sucumbência": ["pagamento ao advogado da parte vencedora, feito pela parte perdedora"],
  "honorários": ["pagamento pelos serviços do advogado"],

  // I
  "idiossincrasia": ["característica particular", "peculiaridade", "traço distintivo"],
  "idôneo": ["apto", "capaz", "confiável", "adequado"],
  "ilação": ["conclusão", "dedução", "inferência"],
  "ilidir": ["refutar", "contestar com provas", "destruir argumento"],
  "imbuído": ["cheio de", "penetrado por (sentimento, ideia)"],
  "iminente": ["prestes a acontecer", "próximo"],
  "imolar": ["sacrificar"],
  "impedimento": ["situação que proíbe o juiz de julgar um caso (por ser parte, por exemplo)"],
  "imperioso": ["urgente", "necessário", "que não pode ser adiado"],
  "impetrar": ["ajuizar (habeas corpus, mandado de segurança)", "requerer judicialmente"],
  "implementar": ["colocar em prática", "fazer", "executar"],
  "imprescindível": ["essencial", "indispensável", "muito necessário"],
  "improcedente": ["sem fundamento", "que não tem razão (pedido)"],
  "impugnar": ["contestar", "discordar", "questionar a validade"],
  "imputar": ["atribuir responsabilidade", "acusar de"],
  "in albis": ["em branco", "sem manifestação", "sem resposta"],
  "in casu": ["neste caso específico", "no caso em questão"],
  "in concreto": ["no caso específico", "na prática"],
  "in dubio pro reo": ["na dúvida, a favor do réu"],
  "in natura": ["ao natural", "em espécie (pagamento em produtos)"],
  "inaudita altera pars": ["sem ouvir o outro lado (em decisões urgentes)"],
  "incipiente": ["inicial", "principiante", "que está começando"],
  "inclusão": ["participação de todos", "integração"],
  "incolumidade": ["segurança", "integridade (física, pública)"],
  "inconteste": ["indiscutível", "que não pode ser negado"],
  "indeferido": ["negado", "rejeitado", "não aceito"],
  "indeferir": ["negar", "rejeitar (um pedido)"],
  "indefiro o pedido": ["nego o pedido"],
  "indagar": ["perguntar", "investigar"],
  "indigitado": ["acusado", "apontado como culpado"],
  "indubitável": ["claro", "sem dúvida", "certo"],
  "induzir": ["levar a", "persuadir", "causar"],
  "inefável": ["indescritível", "que não se pode expressar por palavras"],
  "inequívoco": ["claro", "certo", "que não deixa dúvida"],
  "inerente": ["essencial", "que faz parte de algo", "próprio de"],
  "inexorável": ["inevitável", "que não se pode evitar ou mudar", "implacável"],
  "infligir": ["aplicar (pena, castigo)", "impor sofrimento"],
  "informar": ["comunicar", "avisar"],
  "inócuo": ["inofensivo", "que não prejudica", "sem efeito"],
  "inopino": ["inesperado", "súbito"],
  "inóspito": ["hostil", "desagradável", "não acolhedor"],
  "inquérito": ["investigação policial"],
  "inquerir": ["perguntar", "interrogar", "investigar"],
  "insigne": ["ilustre", "notável", "famoso"],
  "insípido": ["sem sabor", "sem graça", "desinteressante"],
  "insolvente": ["que não pode pagar as dívidas"],
  "instância": ["grau de jurisdição (1ª instância: juiz; 2ª instância: tribunal)"],
  "instar": ["pedir com insistência", "solicitar"],
  "instrução processual": ["fase de coleta de provas no processo"],
  "insubsistente": ["sem base", "sem fundamento", "frágil"],
  "intempestivo": ["fora do prazo", "atrasado", "inoportuno"],
  "interdito proibitório": ["ação para impedir ameaça à posse de um bem"],
  "inter partes": ["entre as partes", "com efeito apenas para os envolvidos no processo"],
  "intimação": ["comunicação oficial de um ato ou decisão no processo"],
  "intimar": ["avisar oficialmente sobre ato ou decisão processual"],
  "intrínseco": ["essencial", "inerente", "que pertence à essência"],
  "inveterado": ["antigo", "arraigado", "crônico"],
  "ipso facto": ["por esse mesmo fato", "automaticamente", "como consequência direta"],
  "irascível": ["irritadiço", "temperamental", "que se irrita facilmente"],
  "irrefutável": ["incontestável", "inquestionável", "que não pode ser negado"],
  "irrisório": ["insignificante", "ridículo", "de pouco valor"],
  "iter criminis": ["caminho do crime", "etapas da execução de um crime"],

  // J
  "jactância": ["presunção", "vaidade", "arrogância"],
  "jazida": ["local onde há minerais", "mina"],
  "judicante": ["que julga", "relativo ao ato de julgar"],
  "jugo": ["domínio", "opressão", "submissão"],
  "juiz leigo": ["cidadão que auxilia o juiz em pequenas causas"],
  "juízo a quo": ["juiz ou tribunal de onde veio o processo (instância inferior)"],
  "juízo ad quem": ["juiz ou tribunal para onde vai o processo (instância superior)"],
  "jurisdição": ["poder de julgar", "área de atuação de um juiz ou tribunal"],
  "jurisprudência": ["conjunto de decisões judiciais sobre um mesmo tema", "entendimento dos tribunais"],
  "jus esperneandi": ["direito de reclamar", "direito de protestar (expressão informal)"],
  "jus possessionis": ["direito de posse", "direito de quem tem a posse"],
  "jus postulandi": ["direito de entrar com ação na justiça sem advogado (em alguns casos)"],
  "justiça gratuita": ["isenção de custos processuais para quem não pode pagar"],

  // L
  "laborar": ["trabalhar", "esforçar-se"],
  "lacônico": ["breve", "resumido", "que fala pouco"],
  "laico": ["não religioso", "secular", "independente de religião"],
  "lapso": ["erro", "falha", "intervalo de tempo"],
  "lassidão": ["cansaço", "fadiga", "moleza"],
  "lastro": ["base", "fundamento", "garantia"],
  "lato sensu": ["em sentido amplo", "de forma geral"],
  "laudo": ["parecer técnico de um especialista", "relatório pericial"],
  "legado": ["herança", "bens deixados em testamento"],
  "lenitivo": ["alívio", "consolo", "suavizante"],
  "letárgico": ["lento", "apático", "sonolento"],
  "levamos a seu conhecimento": ["informamos", "comunicamos"],
  "levar em consideração": ["considerar", "pensar sobre"],
  "LBI (Lei Brasileira de Inclusão)": ["Estatuto da Pessoa com Deficiência"],
  "libelo": ["acusação escrita", "petição inicial (antigo)"],
  "liame": ["ligação", "vínculo", "conexão"],
  "liminar": ["decisão judicial urgente e provisória, no início do processo"],
  "linde": ["limite", "fronteira", "divisa"],
  "litígio": ["disputa judicial", "briga na Justiça", "conflito"],
  "litisconsórcio": ["várias pessoas no mesmo lado do processo (autores ou réus)"],
  "litispendência": ["existência de outro processo idêntico em andamento"],
  "logradouro": ["espaço público (rua, praça)", "endereço"],
  "lograr": ["conseguir", "alcançar", "enganar"],
  "lucros cessantes": ["o que se deixou de ganhar por causa de um dano"],
  "ludibriado": ["enganado", "iludido", "feito de bobo"],

  // M
  "mácula": ["mancha", "defeito", "desonra"],
  "magnânimo": ["generoso", "bondoso", "nobre"],
  "malgrado": ["apesar de", "não obstante", "embora"],
  "maledicência": ["difamação", "calúnia", "falar mal dos outros"],
  "malversação": ["desvio de dinheiro público", "má administração de fundos"],
  "mandado": ["ordem judicial escrita"],
  "mandado de segurança": ["ação para proteger direito líquido e certo contra ato ilegal de autoridade"],
  "manifesto": ["evidente", "claro", "declaração pública"],
  "maquinar": ["planejar secretamente", "tramar"],
  "matiz": ["tonalidade", "aspecto", "nuança"],
  "medida cautelar": ["medida preventiva para garantir o resultado do processo"],
  "megalomaníaco": ["com delírios de grandeza", "extremamente ambicioso"],
  "mendaz": ["mentiroso", "falso", "enganoso"],
  "mens legis": ["o espírito da lei", "a intenção do legislador"],
  "merece prosperar": ["tem razão", "deve ser aceito (o pedido)"],
  "mérito": ["assunto principal do processo", "questão central a ser decidida"],
  "meticuloso": ["cuidadoso", "detalhista", "minucioso"],
  "ministério público": ["órgão que defende os interesses da sociedade e fiscaliza a lei"],
  "minudente": ["detalhado", "minucioso"],
  "minuta": ["rascunho", "primeira versão de um documento"],
  "mister": ["necessário", "importante", "obrigatório"],
  "mitigar": ["aliviar", "diminuir", "suavizar"],
  "mobilidade reduzida": ["dificuldade de locomoção ou movimento"],
  "modificação do regime alimentar": ["mudança de dieta", "alteração na alimentação"],
  "modificar": ["mudar", "alterar"],
  "modus operandi": ["modo de agir", "forma de atuar (especialmente de criminosos)"],
  "moléstia": ["doença"],
  "moratória": ["adiamento do prazo de pagamento de dívida"],
  "mutatis mutandis": ["com as devidas adaptações", "mudando o que deve ser mudado"],

  // N
  "nefasto": ["ruim", "prejudicial", "desastroso"],
  "negativa": ["resposta negativa", "não", "recusa"],
  "negligência": ["descuido", "falta de atenção", "omissão"],
  "neófito": ["iniciante", "novato", "principiante"],
  "nepotismo": ["favorecimento de parentes em cargos públicos"],
  "nexo causal": ["ligação entre a ação/omissão e o resultado/dano"],
  "não obstante": ["apesar disso", "mesmo assim", "contudo"],
  "não tem o condão de afastar": ["não afasta", "não impede", "não elimina"],
  "nocivo": ["prejudicial", "danoso", "que faz mal"],
  "notório": ["conhecido por todos", "público", "evidente"],
  "novel": ["novo", "recente"],
  "núcleo": ["centro", "essência", "parte principal"],
  "nulidade": ["invalidade de um ato processual por defeito grave"],

  // O
  "óbice": ["obstáculo", "impedimento", "dificuldade"],
  "objurgar": ["repreender", "criticar severamente"],
  "oblíquo": ["indireto", "tortuoso", "diagonal"],
  "obliterar": ["apagar", "destruir", "eliminar"],
  "obnubilar": ["escurecer", "confundir (a razão, o entendimento)"],
  "obsequiar": ["presentear", "agradar"],
  "obsoleto": ["ultrapassado", "fora de uso", "antiquado"],
  "obstinado": ["teimoso", "persistente", "que não desiste fácil"],
  "obstar": ["impedir", "dificultar", "opor-se"],
  "obter": ["conseguir", "alcançar"],
  "obtuso": ["pouco inteligente", "limitado", "sem agudeza"],
  "obviar": ["evitar", "remediar", "eliminar (obstáculo)"],
  "oitiva": ["ato de ouvir (testemunhas, partes)"],
  "olvidar": ["esquecer"],
  "oneroso": ["caro", "custoso", "que envolve despesas"],
  "ônus da prova": ["obrigação de provar o que se alega no processo"],
  "ônus": ["obrigação", "encargo", "responsabilidade"],
  "opróbrio": ["vergonha", "desonra", "insulto grave"],
  "opulento": ["rico", "luxuoso", "abundante"],
  "oratória": ["arte de falar em público"],
  "ordenamento jurídico": ["conjunto de leis de um país"],
  "oriundo": ["originário de", "proveniente de"],
  "ostentação": ["exibição de riqueza", "luxo exagerado"],
  "outorgar": ["conceder", "dar", "autorizar"],
  "outrossim": ["além disso", "também", "igualmente"],

  // P
  "pacta sunt servanda": ["os contratos devem ser cumpridos"],
  "paradigma": ["modelo", "padrão", "exemplo"],
  "parcimônia": ["economia", "moderação nos gastos", "contenção"],
  "parecer": ["opinião técnica", "manifestação de especialista ou órgão"],
  "pari passu": ["simultaneamente", "ao mesmo tempo", "em igualdade de condições"],
  "paridade": ["igualdade"],
  "partes": ["pessoas envolvidas no processo (autor, réu, etc.)"],
  "parvo": ["tolo", "ingênuo", "bobo"],
  "passível de": ["sujeito a", "que pode sofrer (punição, multa)"],
  "patente": ["evidente", "claro", "óbvio"],
  "patrono": ["advogado", "defensor"],
  "PcD": ["pessoa com deficiência"],
  "peculiar": ["próprio", "característico", "especial"],
  "pecúlio": ["dinheiro guardado", "economias"],
  "pecuniário": ["relativo a dinheiro"],
  "peita": ["suborno"],
  "pejorativo": ["depreciativo", "negativo", "ofensivo"],
  "penhora": ["apreensão de bens do devedor para pagar dívida"],
  "peremptório": ["decisivo", "definitivo", "que não admite contestação"],
  "performance": ["desempenho", "atuação"],
  "perfunctório": ["superficial", "feito de qualquer maneira", "descuidado"],
  "perícia": ["exame técnico feito por especialista para esclarecer fatos"],
  "periclitar": ["correr perigo", "estar em risco"],
  "periculum in mora": ["perigo da demora (risco de dano se a decisão demorar)"],
  "perito": ["especialista nomeado pelo juiz para dar parecer técnico"],
  "perjúrio": ["falso testemunho sob juramento"],
  "permear": ["penetrar", "atravessar", "influenciar"],
  "perquirir": ["investigar", "perguntar com insistência"],
  "per se": ["por si mesmo", "intrinsecamente", "em si"],
  "perscrutar": ["examinar com atenção", "investigar minuciosamente"],
  "perspicaz": ["astuto", "inteligente", "que percebe as coisas com facilidade"],
  "pertinaz": ["persistente", "obstinado", "teimoso"],
  "petição inicial": ["primeiro pedido feito à Justiça, que dá início ao processo"],
  "petição": ["pedido escrito dirigido ao juiz"],
  "pleitear": ["pedir judicialmente", "solicitar", "reivindicar"],
  "pleito": ["pedido", "disputa judicial", "demanda"],
  "plenário": ["local de reunião de todos os membros de um tribunal ou assembleia"],
  "plissado": ["com dobras", "pregueado"],
  "plausível": ["aceitável", "provável", "que parece verdadeiro"],
  "ponderar": ["pensar com cuidado", "refletir", "considerar"],
  "por conseguinte": ["portanto", "logo", "assim sendo"],
  "portanto": ["logo", "assim", "por isso"],
  "porventura": ["talvez", "por acaso", "possivelmente"],
  "postergar": ["adiar", "deixar para depois"],
  "postular": ["pedir", "requerer", "solicitar em juízo"],
  "potestade": ["poder", "autoridade"],
  "praxe": ["costume", "rotina", "prática habitual"],
  "preâmbulo": ["introdução", "parte inicial (de uma lei, constituição)"],
  "precário": ["instável", "inseguro", "temporário"],
  "precatório": ["ordem de pagamento de dívida do governo após condenação judicial"],
  "precípuo": ["principal", "essencial", "fundamental"],
  "precluir": ["perder o direito de praticar um ato processual por não fazê-lo no prazo"],
  "preclusão": ["perda do direito de agir no processo por não ter feito no momento certo"],
  "preconizar": ["recomendar", "defender", "elogiar publicamente"],
  "prefacial": ["inicial", "preliminar"],
  "prefeito": ["perfeito", "completo (termo menos comum)"],
  "prejudicado": ["analisado e perdido o objeto (recurso, pedido)"],
  "prejudicial": ["que causa dano", "nocivo"],
  "preliminares": ["questões iniciais discutidas antes do mérito do processo"],
  "premente": ["urgente", "imediato", "que pressiona"],
  "premonitório": ["que avisa antes", "que prevê o futuro"],
  "preponderar": ["predominar", "ter mais peso ou importância"],
  "preposto": ["representante da empresa em audiência"],
  "prerrogativa": ["privilégio", "vantagem", "direito especial"],
  "prescindir": ["dispensar", "abrir mão de", "não precisar de"],
  "prescrição": ["perda do direito de entrar com ação ou de punir por ter passado muito tempo"],
  "prescrever": ["perder a validade (direito, crime) pelo tempo", "determinar"],
  "presumir": ["supor", "achar provável"],
  "pretérito": ["passado"],
  "prevaricação": ["crime do funcionário público que atrasa ou deixa de fazer seu trabalho por interesse pessoal"],
  "primazia": ["prioridade", "superioridade", "primeiro lugar"],
  "pristino": ["original", "antigo", "puro"],
  "pro rata": ["proporcionalmente", "dividido de forma proporcional"],
  "probatório": ["relativo a provas", "que serve para provar"],
  "proceda-se à intimação da parte autora": ["avise quem fez o pedido"],
  "procedente": ["com fundamento", "que tem razão (pedido)"],
  "processo": ["conjunto de atos na Justiça para resolver um conflito"],
  "procrastinar": ["adiar", "deixar para depois", "enrolar"],
  "procuração ad judicia": ["documento que dá poderes ao advogado para atuar no processo"],
  "procuração": ["documento que autoriza alguém a agir em nome de outra pessoa"],
  "prodigo": ["que gasta demais", "esbanjador"],
  "profícuo": ["útil", "proveitoso", "vantajoso"],
  "proferir": ["dar (sentença, decisão)", "emitir", "pronunciar"],
  "profuso": ["abundante", "farto", "em grande quantidade"],
  "prognóstico": ["previsão"],
  "prolação": ["ato de proferir (sentença, decisão)"],
  "prolator": ["quem profere (a sentença, decisão)"],
  "prolegômenos": ["introdução longa", "considerações iniciais"],
  "prolixo": ["longo demais", "excessivamente detalhado", "que fala ou escreve muito"],
  "promotor de justiça": ["membro do Ministério Público que atua na primeira instância"],
  "promulgar": ["publicar oficialmente uma lei para que entre em vigor"],
  "propalar": ["divulgar", "espalhar (notícia)"],
  "propedêutica": ["introdução", "conhecimentos preliminares"],
  "propender": ["inclinar-se a", "ter tendência a"],
  "propugnar": ["defender", "sustentar", "lutar por"],
  "prorrogar": ["adiar", "estender o prazo"],
  "proscrito": ["banido", "proibido", "excluído"],
  "proselitismo": ["tentativa de converter outros a uma ideia ou religião"],
  "prosopopeia": ["linguagem empolada", "estilo pomposo", "personificação"],
  "prosseguir": ["continuar", "seguir em frente"],
  "protocolo": ["registro de entrada de documentos"],
  "protelar": ["adiar", "atrasar"],
  "provento": ["renda", "salário (especialmente de aposentados e pensionistas)"],
  "provisão": ["abastecimento", "suprimento", "medida preventiva"],
  "prudência": ["cautela", "precaução", "bom senso"],
  "pugnar": ["lutar", "defender com empenho", "esforçar-se"],
  "pusilânime": ["covarde", "medroso", "fraco de espírito"],

  // Q
  "queixa-crime": ["ação penal iniciada pela vítima em crimes específicos"],
  "querela": ["disputa", "briga", "discussão"],
  "quesito": ["pergunta (feita a jurados ou peritos)"],
  "quimera": ["ilusão", "fantasia", "sonho impossível"],
  "quitação": ["comprovante de pagamento", "ato de declarar uma dívida paga"],

  // R
  "ratificar": ["confirmar", "validar", "aprovar o que foi feito"],
  "rechaçar": ["rejeitar", "repelir", "recusar com força"],
  "recesso judiciário": ["férias dos tribunais e juízes"],
  "recôndito": ["escondido", "secreto", "profundo"],
  "recorrente": ["quem entra com recurso"],
  "recorrido": ["quem responde ao recurso"],
  "recrudescer": ["intensificar", "agravar", "piorar novamente"],
  "redarguir": ["rebater", "contestar", "responder argumentando"],
  "redimir": ["libertar", "salvar", "compensar um erro"],
  "reduto": ["refúgio", "lugar seguro"],
  "referendar": ["aprovar", "confirmar", "dar apoio oficial"],
  "refrear": ["conter", "controlar", "moderar"],
  "refutar": ["contestar com argumentos", "negar provando o contrário"],
  "reiterar": ["repetir", "reafirmar", "dizer novamente"],
  "relator": ["juiz responsável por analisar e apresentar o caso no tribunal"],
  "relegar": ["deixar de lado", "desprezar", "colocar em segundo plano"],
  "remanescente": ["restante", "o que sobra"],
  "remissão": ["perdão (de dívida, de pena)", "quitação"],
  "remoto": ["distante (no tempo ou espaço)", "antigo"],
  "renitente": ["resistente", "obstinado", "teimoso em não cumprir"],
  "renúncia": ["desistência de um direito"],
  "repercussão geral": ["requisito para que o STF julgue um recurso, exigindo relevância social, política, econômica ou jurídica"],
  "repercussão": ["efeito", "consequência", "ressonância"],
  "réplica": ["resposta do autor à contestação do réu"],
  "réprobo": ["condenado", "reprovado", "mau"],
  "requerer": ["pedir", "solicitar formalmente"],
  "requisição": ["pedido formal", "solicitação oficial"],
  "requisitar": ["pedir formalmente", "solicitar oficialmente"],
  "rescindir": ["anular (contrato)", "cancelar"],
  "resiliência": ["capacidade de se recuperar de dificuldades"],
  "resquício": ["vestígio", "sinal", "resto"],
  "ressalva": ["observação", "exceção", "restrição"],
  "ressarcir": ["indenizar", "reparar o prejuízo"],
  "retificar": ["corrigir", "consertar", "emendar"],
  "retórica": ["arte de falar bem", "discurso persuasivo (às vezes vazio)"],
  "revelia": ["situação em que o réu não se defende no prazo"],
  "revogar": ["anular (uma lei, uma decisão)", "cancelar"],
  "rito": ["procedimento", "conjunto de regras de um processo"],
  "rubrica": ["assinatura abreviada", "título de seção"],
  "rufião": ["quem explora a prostituição alheia"],

  // S
  "sacramentar": ["confirmar", "tornar definitivo"],
  "salutar": ["saudável", "benéfico", "proveitoso"],
  "sanar": ["corrigir (um erro, um problema)", "resolver"],
  "sancionar": ["aprovar e tornar lei (pelo presidente)", "punir"],
  "sanear": ["limpar", "higienizar", "corrigir irregularidades (no processo)"],
  "sapiência": ["sabedoria", "grande conhecimento"],
  "sazonar": ["amadurecer"],
  "secular": ["que dura um século", "antigo", "não religioso"],
  "sedicioso": ["rebelde", "que incita à revolta"],
  "segredo de justiça": ["processo que não pode ser divulgado publicamente"],
  "Seguridade Social": ["sistema de proteção social (saúde, previdência, assistência)"],
  "sentença": ["decisão final do juiz no processo de primeira instância"],
  "sequela": ["consequência (geralmente ruim)", "lesão permanente"],
  "serventuário da justiça": ["funcionário do cartório judicial"],
  "sibilino": ["enigmático", "misterioso", "difícil de entender"],
  "signatário": ["pessoa que assina um documento"],
  "silogismo": ["raciocínio lógico com premissas e conclusão"],
  "simulacro": ["imitação", "aparência falsa"],
  "sine qua non": ["condição indispensável", "essencial", "sem a qual não"],
  "sinuoso": ["curvo", "tortuoso", "com muitas voltas"],
  "sisudo": ["sério", "calado", "carrancudo"],
  "soberba": ["orgulho excessivo", "arrogância", "presunção"],
  "sobrestar": ["suspender (o processo)", "adiar"],
  "sopesar": ["avaliar", "considerar com cuidado", "ponderar"],
  "sortir efeito": ["produzir resultado", "funcionar"],
  "sub judice": ["em julgamento", "pendente de decisão judicial"],
  "subjacente": ["que está por baixo", "implícito", "fundamental"],
  "subjetivo": ["pessoal", "parcial", "baseado em opiniões"],
  "subjugar": ["dominar", "submeter"],
  "sublimar": ["elevar", "purificar", "transformar (sentimento negativo em algo positivo)"],
  "sub-reptício": ["feito às escondidas", "oculto", "fraudulento"],
  "subscritor": ["quem assina um documento"],
  "subserviente": ["submisso", "obediente demais", "servil"],
  "subsidiar": ["ajudar financeiramente", "fornecer base para"],
  "subsidiariedade": ["caráter secundário", "aplicação apenas se a norma principal não resolver"],
  "subsidiário": ["secundário", "complementar", "que ajuda"],
  "subsistir": ["continuar a existir", "permanecer"],
  "substabelecimento": ["transferência de poderes do advogado para outro colega"],
  "subsunção": ["encaixe de um fato real na descrição da lei"],
  "subterfúgio": ["desculpa", "evasiva", "meio habilidoso para escapar de dificuldade"],
  "sucumbência": ["derrota no processo (quem perde paga os honorários do advogado da outra parte)"],
  "sucumbir": ["ceder", "desistir", "morrer"],
  "súmula vinculante": ["decisão resumida do STF que obriga todo o Judiciário"],
  "súmula": ["resumo de decisões anteriores de um tribunal sobre um tema"],
  "supedâneo": ["base", "fundamento", "apoio"],
  "supérfluo": ["desnecessário", "dispensável", "excessivo"],
  "superveniente": ["que acontece depois", "posterior", "subsequente"],
  "suplantar": ["superar", "vencer", "substituir"],
  "supramencionado": ["citado acima", "mencionado antes"],
  "suprir": ["completar", "fornecer o que falta", "remediar"],
  "suscitar": ["provocar", "despertar", "levantar (uma questão)"],
  "suspeição": ["dúvida sobre a imparcialidade do juiz (por amizade, inimizade, etc.)"],
  "sustar": ["suspender", "interromper"],

  // T
  "taciturno": ["calado", "silencioso", "triste"],
  "tácito": ["implícito", "não expresso claramente, mas entendido"],
  "talante": ["vontade", "capricho", "desejo"],
  "tampouco": ["também não", "nem"],
  "tangível": ["concreto", "palpável", "que se pode tocar"],
  "taxativo": ["restrito", "limitado", "que não admite outras interpretações"],
  "tema em epígrafe": ["assunto mencionado no título", "tema em discussão"],
  "temerário": ["arriscado", "imprudente", "que age sem pensar"],
  "temos a informar que": ["informamos"],
  "temos em nosso poder": ["recebemos", "temos conosco"],
  "tenaz": ["persistente", "firme", "que não desiste"],
  "tergiversar": ["desviar do assunto", "mudar de conversa", "hesitar"],
  "termo circunstanciado": ["registro de ocorrência de infração de menor potencial ofensivo"],
  "testemunha": ["pessoa que depõe sobre fatos que presenciou ou tem conhecimento"],
  "testamento": ["documento que expressa a vontade de alguém sobre seus bens após a morte"],
  "testilha": ["disputa", "debate", "discussão"],
  "torpe": ["vergonhoso", "indecente", "repugnante"],
  "trâmite": ["procedimento", "andamento de um processo", "etapas"],
  "transcender": ["superar", "ir além de", "ultrapassar"],
  "transigir": ["fazer acordo", "ceder em parte para resolver conflito"],
  "trânsito em julgado": ["decisão judicial final, da qual não cabe mais recurso"],
  "transladar": ["transferir", "copiar", "mudar de lugar"],
  "translúcido": ["que deixa passar a luz, mas não permite ver com nitidez"],
  "transmudar": ["transformar", "mudar completamente"],
  "transversal": ["que atravessa", "que cruza"],
  "transtorno do espectro autista": ["autismo", "condição relacionada ao desenvolvimento neurológico"],
  "travar uma discussão": ["discutir", "debater"],
  "tréplica": ["resposta do réu à réplica do autor"],
  "trivial": ["comum", "banal", "sem importância"],
  "tutela antecipada": ["decisão que adianta os efeitos da sentença final, por urgência"],
  "tutela jurisdicional": ["proteção dada pela Justiça"],
  "tutela": ["proteção", "amparo (legal, de menor)"],

  // U
  "ubíquo": ["presente em todo lugar ao mesmo tempo", "onipresente"],
  "ulterior": ["posterior", "seguinte", "que vem depois"],
  "ultra petita": ["decisão que vai além do que foi pedido pelas partes"],
  "ultraje": ["ofensa grave", "insulto"],
  "uníssono": ["em uma só voz", "em concordância"],
  "usucapião": ["forma de adquirir propriedade de um bem pelo uso contínuo por certo tempo"],
  "usufruto": ["direito de usar e gozar de um bem que pertence a outra pessoa"],
  "usura": ["cobrança de juros excessivos", "agiotagem"],

  // V
  "vacatio legis": ["período entre a publicação de uma lei e sua entrada em vigor"],
  "vacilante": ["hesitante", "indeciso", "instável"],
  "vadio": ["desocupado", "que não trabalha"],
  "vade mecum": ["livro com as principais leis, usado por estudantes e profissionais do Direito"],
  "vai acarretar": ["vai causar", "vai resultar em"],
  "validação": ["confirmação", "ato de tornar válido"],
  "valia": ["valor", "importância"],
  "vândalo": ["que destrói bens públicos ou privados"],
  "vanguarda": ["que está à frente", "inovador"],
  "vaticinar": ["prever", "profetizar"],
  "veemência": ["intensidade", "vigor", "paixão (ao falar)"],
  "velado": ["oculto", "disfarçado", "secreto"],
  "venal": ["que se vende", "corruptível"],
  "vênia": ["licença", "permissão (para discordar, por exemplo)"],
  "venerar": ["respeitar profundamente", "adorar", "cultuar"],
  "veracidade": ["qualidade do que é verdadeiro"],
  "verborragia": ["falar muito e sem conteúdo", "excesso de palavras"],
  "veredito": ["decisão dos jurados no tribunal do júri"],
  "vereda": ["caminho estreito", "trilha"],
  "vernáculo": ["língua própria de um país", "idioma nacional", "autêntico"],
  "verossímil": ["provável", "que parece verdadeiro", "plausível"],
  "versado": ["experiente", "que tem conhecimento sobre algo"],
  "vetar": ["proibir", "não aprovar (uma lei, pelo presidente)"],
  "vetusto": ["muito antigo", "velho"],
  "vexame": ["vergonha", "humilhação"],
  "vexatório": ["que causa vergonha ou humilhação"],
  "via de regra": ["geralmente", "normalmente"],
  "viabilizar": ["tornar possível", "fazer acontecer"],
  "vicissitude": ["mudança", "alternância (de sorte, de situações)", "contratempo"],
  "vindicar": ["reivindicar", "exigir o que é seu por direito"],
  "vilipendiar": ["desprezar", "humilhar", "tratar com desdém"],
  "vindouro": ["futuro", "próximo", "que está por vir"],
  "violabilidade": ["qualidade do que pode ser violado"],
  "virtuose": ["artista muito habilidoso", "expert", "mestre"],
  "vislumbrar": ["enxergar parcialmente", "perceber de leve", "imaginar"],
  "vitaliciedade": ["cargo garantido por toda a vida (para juízes, por exemplo)"],
  "vociferar": ["gritar", "falar em voz alta e com raiva"],
  "volátil": ["que muda facilmente", "instável", "que evapora rápido"],
  "volitivo": ["relativo à vontade"],
  "volúvel": ["inconstante", "que muda de ideia facilmente"],
  "vultoso": ["grande (em quantidade, valor)", "considerável"],

  // X
  "xenofobia": ["aversão a estrangeiros", "medo ou ódio do que é diferente ou estrangeiro"],
  "xilografia": ["gravura em madeira", "arte de gravar em madeira"],

  // Z
  "zombaria": ["deboche", "caçoada", "escárnio"],

  // Expressões (mantidas e expandidas)
  "a posteriori": ["depois", "posteriormente", "após a experiência"],
  "a priori": ["antes", "previamente", "antes da experiência"],
  "ab initio": ["desde o começo", "do início"],
  "ad cautelam": ["por precaução", "por segurança"],
  "ad hoc": ["para este fim", "específico para o caso", "para isso"],
  "amicus curiae": ["amigo da corte", "colaborador do tribunal"],
  "data máxima vênia": ["com o máximo respeito", "pedindo licença (para discordar)"],
  "de antemão": ["antecipadamente", "previamente"],
  "de cujus": ["pessoa falecida (no inventário)", "o falecido"],
  "em consonância com": ["de acordo com", "em harmonia com"],
  "em conformidade com": ["de acordo com", "seguindo as regras de"],
  "em decorrência de": ["por causa de", "como resultado de"],
  "em detrimento de": ["prejudicando", "em prejuízo de"],
  "em face de": ["diante de", "perante", "considerando"],
  "em que pese": ["apesar de", "embora"],
  "em se tratando de": ["sobre", "quando se trata de"],
  "em suma": ["resumindo", "em resumo"],
  "em virtude de": ["por causa de", "devido a"],
  "erga omnes": ["válido para todos", "com efeito geral"],
  "ex nunc": ["a partir de agora", "com efeito para o futuro"],
  "ex tunc": ["desde o início", "com efeito retroativo"],
  "extra petita": ["decisão fora do que foi pedido"],
  "fumus boni iuris": ["aparência de bom direito", "sinal de que o direito provavelmente existe"],
  "grosso modo": ["de modo geral", "aproximadamente", "sem detalhes"],
  "habeas corpus": ["ação para proteger o direito de liberdade"],
  "haja vista": ["considerando", "tendo em vista", "levando em conta"],
  "in albis": ["em branco", "sem manifestação"],
  "in casu": ["neste caso específico", "no caso em questão"],
  "in concreto": ["no caso específico", "na prática"],
  "in dubio pro reo": ["na dúvida, a favor do réu"],
  "in natura": ["ao natural", "em espécie"],
  "inaudita altera pars": ["sem ouvir o outro lado"],
  "inter partes": ["entre as partes", "com efeito apenas para os envolvidos"],
  "ipso facto": ["por esse mesmo fato", "automaticamente"],
  "jus esperneandi": ["direito de reclamar (informal)"],
  "jus postulandi": ["direito de ir à Justiça sem advogado (em alguns casos)"],
  "lato sensu": ["em sentido amplo", "de forma geral"],
  "mens legis": ["o espírito da lei", "a intenção do legislador"],
  "modus operandi": ["modo de agir", "forma de atuar"],
  "mutatis mutandis": ["com as devidas adaptações", "mudando o que deve ser mudado"],
  "não obstante": ["apesar disso", "mesmo assim", "contudo"],
  "no que tange a": ["sobre", "em relação a", "quanto a"],
  "pacta sunt servanda": ["os contratos devem ser cumpridos"],
  "pari passu": ["simultaneamente", "ao mesmo tempo", "em igualdade de condições"],
  "per se": ["por si mesmo", "intrinsecamente", "em si"],
  "periculum in mora": ["perigo da demora", "risco de dano pela demora da decisão"],
  "pro rata": ["proporcionalmente", "dividido de forma proporcional"],
  "sine qua non": ["condição indispensável", "essencial", "sem a qual não"],
  "stricto sensu": ["em sentido restrito", "de forma específica"],
  "sub judice": ["em julgamento", "pendente de decisão judicial"],
  "ultra petita": ["decisão que vai além do que foi pedido"],
  "via de regra": ["geralmente", "normalmente"]
};

// Exporta o glossário para ser utilizado por outros scripts
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GLOSSARY };
} else if (typeof define === 'function' && define.amd) {
  define([], function() {
    return { GLOSSARY };
  });
}